

//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pharmacy.BusinessLayer.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PharmacyContainer : DbContext
{
    public PharmacyContainer()
        : base("name=PharmacyContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Drug> DrugSet { get; set; }

    public DbSet<InventoryEvent> InventoryEventSet { get; set; }

    public DbSet<Position> PositionSet { get; set; }

    public DbSet<ReplenishmentOrder> ReplenishmentOrderSet { get; set; }

    public DbSet<Prescription> PrescriptionSet { get; set; }

    public DbSet<Item> ItemSet { get; set; }

    public DbSet<Customer> CustomerSet { get; set; }

}

}

